### ISSUE TITLE
Scraper does not work for 2020

### ISSUE THREAD

**Issue by AD9000** [csesoc/notangles#58]
Find and eliminate the bug!

**Comment by Mysterise** [comment]
Do you have any idea what's causing the scraper to not work for 2020, even though it works for 2019? Dump all the info you have here!

**Comment by AD9000** [comment]
So I was looking into it, and found that the source is actually the change in the reference of finding classifying a class into a term.
What we need is a more robust way of classifying the classes and courses.

Plus, there's also the issue that it broke in the first place. The scraper should be "self healing" so it breaking is not good. This is mainly because I wanted it to break if any issue popped up when we were building it. So we've gotta deal with the errors when the pop up. They are in a try catch block but I just bubble the error up and let the scraper break.
For this problem I suggest bumping up the priority of the logger. We can check log files and put out patches whenever without having to worry about the scraper breaking

**Comment by AD9000** [comment]
The bug has been fixed, and team has moved on to a new scraper.
