### ISSUE TITLE
Stop deleting timetables every time you switch over to a new term

### ISSUE THREAD

**Issue by xarmebx** [csesoc/notangles#807]
it takes a long time to make a custom timetable with custom colors, pls stop wiping them whenever you switch terms.
I've had to remake the same timetable 3 times over because it keeps getting wiped every time you revert from 23T3 to 24T1 :l

**Comment by Shzmj** [comment]
Hello, thank you for raising this issue- hopefully this would be remedied by our upcoming features for releasing custom colours (#788) and switching between multiple terms (#792)!

**Comment by xarmebx** [comment]
yummers 😋
