### ISSUE TITLE
task: Expanded Search Bar redesign

### ISSUE THREAD

**Issue by Shzmj** [csesoc/notangles#818]
The redesign has been made by our amazing 2023 UIUX team, time to update the search bar design 😱 

![image](https://github.com/devsoc-unsw/notangles/assets/109339363/323d8d32-afe2-4be5-9bfe-dc4d3b4cd289)

**Comment by chanboba** [comment]
https://github.com/devsoc-unsw/notangles/tree/feature/chanel-818-search-bar
![image](https://github.com/devsoc-unsw/notangles/assets/112926046/8028d2d9-f998-495b-af67-1618dd5a2934)
![image](https://github.com/devsoc-unsw/notangles/assets/112926046/5dd47d08-5b59-4621-b29e-67111b4d6687)

Current design above - will need to talk with @nikkichins to fix the front-end design and then I'll work on school --> faculty mapping.
